// <auto-generated />
using System;
using AI.Caller.Phone;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.Caller.Phone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212072721_AddScenarioToBatchJob")]
    partial class AddScenarioToBatchJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AI.Caller.Phone.Entities.AICustomerServiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoAnswerDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DefaultSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("DefaultTtsTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultWelcomeScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AICustomerServiceSettings");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.BatchCallJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSelectLine")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScenarioRecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedLineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TtsTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ScenarioRecordingId");

                    b.HasIndex("TtsTemplateId");

                    b.ToTable("BatchCallJobs");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.CallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BatchCallJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallScenario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalleeNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CalleeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallerNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitiationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedContent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScenarioRecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatchCallJobId");

                    b.HasIndex("CallId")
                        .HasDatabaseName("IX_CallLogs_CallId");

                    b.HasIndex("CallScenario")
                        .HasDatabaseName("IX_CallLogs_CallScenario");

                    b.HasIndex("CalleeUserId")
                        .HasDatabaseName("IX_CallLogs_CalleeUserId");

                    b.HasIndex("CallerUserId")
                        .HasDatabaseName("IX_CallLogs_CallerUserId");

                    b.HasIndex("Direction")
                        .HasDatabaseName("IX_CallLogs_Direction");

                    b.HasIndex("ScenarioRecordingId");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_CallLogs_StartTime");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CallLogs_Status");

                    b.ToTable("CallLogs");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Contacts_PhoneNumber");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Contacts_UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.DtmfInputRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InputTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("InputValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .HasDatabaseName("IX_DtmfInputRecords_CallId");

                    b.HasIndex("CallLogId");

                    b.HasIndex("InputTime")
                        .HasDatabaseName("IX_DtmfInputRecords_InputTime");

                    b.HasIndex("SegmentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("DtmfInputRecords");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.DtmfInputTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("BackspaceKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ErrorText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<char>("TerminationKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeoutText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ValidatorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputType")
                        .HasDatabaseName("IX_DtmfInputTemplates_InputType");

                    b.ToTable("DtmfInputTemplates");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.MonitoringSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallLogId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InterventionTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .HasDatabaseName("IX_MonitoringSessions_CallId");

                    b.HasIndex("CallLogId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MonitoringSessions_IsActive");

                    b.HasIndex("MonitorUserId")
                        .HasDatabaseName("IX_MonitoringSessions_MonitorUserId");

                    b.ToTable("MonitoringSessions");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.PlaybackControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallLogId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("CurrentSegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastInterventionSegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkippedSegments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlaybackControls_CallId");

                    b.HasIndex("CallLogId");

                    b.ToTable("PlaybackControls");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.Ringtone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("IX_Ringtones_IsSystem");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Ringtones_Type");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("IX_Ringtones_UploadedBy");

                    b.ToTable("Ringtones");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.ScenarioRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ScenarioRecordings_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ScenarioRecordings_IsActive");

                    b.ToTable("ScenarioRecordings");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.ScenarioRecordingSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("DtmfTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DtmfVariableName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextSegmentIdOnFalse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextSegmentIdOnTrue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioRecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsVariables")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DtmfTemplateId");

                    b.HasIndex("ScenarioRecordingId")
                        .HasDatabaseName("IX_ScenarioRecordingSegments_ScenarioRecordingId");

                    b.HasIndex("SegmentOrder")
                        .HasDatabaseName("IX_ScenarioRecordingSegments_SegmentOrder");

                    b.ToTable("ScenarioRecordingSegments");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SipAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("DefaultLineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SipPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SipServer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SipUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLineId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SipAccounts_IsActive");

                    b.HasIndex("SipUsername")
                        .IsUnique()
                        .HasDatabaseName("IX_SipAccounts_SipUsername");

                    b.ToTable("SipAccounts");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SipLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundProxy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ProxyServer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SipLines_IsActive");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_SipLines_Priority");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_SipLines_Region");

                    b.ToTable("SipLines");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SystemRingtoneSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultIncomingRingtoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultRingbackToneId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefaultIncomingRingtoneId");

                    b.HasIndex("DefaultRingbackToneId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SystemRingtoneSettings");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.TtsTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("包含占位符的内容模板, e.g., '您好{CustomerName}，欢迎使用我们的服务。'");

                    b.Property<string>("EndingSpeech")
                        .HasColumnType("TEXT")
                        .HasComment("循环播放结束后，最终播报一次的内容。");

                    b.Property<bool>("HangupAfterPlay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PauseBetweenPlaysInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpeechRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TtsTemplates");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.TtsVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("在模板中使用的占位符，不含大括号, e.g., 'CustomerName'");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TtsVariables");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRecording")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAI")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SipAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SipRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SipAccountId")
                        .HasDatabaseName("IX_Users_SipAccountId");

                    b.HasIndex("SipRegistered")
                        .HasDatabaseName("IX_Users_SipRegistered");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoRecording = false,
                            EnableAI = false,
                            IsAdmin = false,
                            Password = "password123",
                            SipRegistered = false,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.UserRingtoneSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int?>("IncomingRingtoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RingbackToneId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomingRingtoneId");

                    b.HasIndex("RingbackToneId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRingtoneSettings_UserId");

                    b.ToTable("UserRingtoneSettings");
                });

            modelBuilder.Entity("AI.Caller.Phone.Models.Recording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SipUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Recordings_StartTime");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Recordings_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Recordings_UserId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("SipAccountSipLine", b =>
                {
                    b.Property<int>("SipAccountsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableLinesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SipAccountsId", "AvailableLinesId");

                    b.HasIndex("AvailableLinesId");

                    b.ToTable("SipAccountSipLine");
                });

            modelBuilder.Entity("TtsTemplateVariable", b =>
                {
                    b.Property<int>("TtsTemplatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariablesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TtsTemplatesId", "VariablesId");

                    b.HasIndex("VariablesId");

                    b.ToTable("TtsTemplateVariable");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.BatchCallJob", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("AI.Caller.Phone.Entities.ScenarioRecording", "ScenarioRecording")
                        .WithMany()
                        .HasForeignKey("ScenarioRecordingId");

                    b.HasOne("AI.Caller.Phone.Entities.TtsTemplate", "TtsTemplate")
                        .WithMany()
                        .HasForeignKey("TtsTemplateId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ScenarioRecording");

                    b.Navigation("TtsTemplate");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.CallLog", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.BatchCallJob", "BatchCallJob")
                        .WithMany("CallLogs")
                        .HasForeignKey("BatchCallJobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Caller.Phone.Entities.User", "CalleeUser")
                        .WithMany()
                        .HasForeignKey("CalleeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.User", "CallerUser")
                        .WithMany()
                        .HasForeignKey("CallerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.ScenarioRecording", "ScenarioRecording")
                        .WithMany()
                        .HasForeignKey("ScenarioRecordingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BatchCallJob");

                    b.Navigation("CalleeUser");

                    b.Navigation("CallerUser");

                    b.Navigation("ScenarioRecording");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.Contact", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.User", null)
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI.Caller.Phone.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.DtmfInputRecord", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.CallLog", null)
                        .WithMany("DtmfInputs")
                        .HasForeignKey("CallLogId");

                    b.HasOne("AI.Caller.Phone.Entities.ScenarioRecordingSegment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.DtmfInputTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Segment");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.MonitoringSession", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.CallLog", null)
                        .WithMany("MonitoringSessions")
                        .HasForeignKey("CallLogId");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.PlaybackControl", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.CallLog", null)
                        .WithMany("PlaybackControls")
                        .HasForeignKey("CallLogId");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.Ringtone", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.ScenarioRecordingSegment", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.DtmfInputTemplate", "DtmfTemplate")
                        .WithMany()
                        .HasForeignKey("DtmfTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.ScenarioRecording", "ScenarioRecording")
                        .WithMany("Segments")
                        .HasForeignKey("ScenarioRecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DtmfTemplate");

                    b.Navigation("ScenarioRecording");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SipAccount", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.SipLine", "DefaultLine")
                        .WithMany()
                        .HasForeignKey("DefaultLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultLine");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SystemRingtoneSettings", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.Ringtone", "DefaultIncomingRingtone")
                        .WithMany()
                        .HasForeignKey("DefaultIncomingRingtoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AI.Caller.Phone.Entities.Ringtone", "DefaultRingbackTone")
                        .WithMany()
                        .HasForeignKey("DefaultRingbackToneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AI.Caller.Phone.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultIncomingRingtone");

                    b.Navigation("DefaultRingbackTone");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.User", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.SipAccount", "SipAccount")
                        .WithMany("Users")
                        .HasForeignKey("SipAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SipAccount");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.UserRingtoneSettings", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.Ringtone", "IncomingRingtone")
                        .WithMany()
                        .HasForeignKey("IncomingRingtoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.Ringtone", "RingbackTone")
                        .WithMany()
                        .HasForeignKey("RingbackToneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AI.Caller.Phone.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingRingtone");

                    b.Navigation("RingbackTone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SipAccountSipLine", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.SipLine", null)
                        .WithMany()
                        .HasForeignKey("AvailableLinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.Caller.Phone.Entities.SipAccount", null)
                        .WithMany()
                        .HasForeignKey("SipAccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TtsTemplateVariable", b =>
                {
                    b.HasOne("AI.Caller.Phone.Entities.TtsTemplate", null)
                        .WithMany()
                        .HasForeignKey("TtsTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.Caller.Phone.Entities.TtsVariable", null)
                        .WithMany()
                        .HasForeignKey("VariablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.BatchCallJob", b =>
                {
                    b.Navigation("CallLogs");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.CallLog", b =>
                {
                    b.Navigation("DtmfInputs");

                    b.Navigation("MonitoringSessions");

                    b.Navigation("PlaybackControls");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.ScenarioRecording", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.SipAccount", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AI.Caller.Phone.Entities.User", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
